project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "files/"
    # - "projects/"

website:
  title: "DataSquared"
  site-url: "https://www.datasqua.red"

  favicon: "/files/img/favicon.png"

  navbar:
    pinned: true
    right:
      - services.qmd
      - text: "Contact"
        href: "mailto:enquiries@datasqua.red"
        aria-label: Email
      - text: "Privacy Policy"
        file: privacy.qmd
      # - icon: envelope
      #   href: "mailto:info@datasqua.red"
      #   aria-label: Email
      # - icon: slack
      #   href: "https://danielpetterson.slack.com"
      #   aria-label: Slack

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var copyright_year >}} by [{{< var primary.name >}}]({{< var primary.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var primary.github >}})

format:
  html:
    theme:
      - brand
    # css: html/custom.scss
    # toc: true
    highlight-style: monokai



